<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreCvRequest;
use App\Http\Requests\UpdateCvRequest;
use App\Models\UserCv;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Log;

class FreeCvController extends Controller
{
    /**
     * Display a listing of CVs (public only for guests, all for authenticated users).
     */
    public function index(Request $request)
    {
        $query = UserCv::with(['user', 'workExperiences', 'educationEntries', 'certifications', 'languages']);

        // If not authenticated, only show public CVs
        if (!Auth::check()) {
            $query->public();
        } else {
            // Optionally filter by current user's CVs
            if ($request->boolean('mine')) {
                $query->where('user_id', Auth::id());
            } else {
                $query->public();
            }
        }

        // Search filter
        if ($request->has('search') && $request->search) {
            $search = $request->search;
            $query->where(function ($q) use ($search) {
                $q->where('full_name', 'like', "%{$search}%")
                    ->orWhere('title', 'like', "%{$search}%")
                    ->orWhere('summary', 'like', "%{$search}%");
            });
        }

        // Skills filter
        if ($request->has('skills') && $request->skills) {
            $query->whereJsonContains('skills', $request->skills);
        }

        // Location filter
        if ($request->has('location') && $request->location) {
            $query->where(function ($q) use ($request) {
                $q->where('city', 'like', "%{$request->location}%")
                    ->orWhere('country', 'like', "%{$request->location}%");
            });
        }

        $perPage = $request->get('per_page', 15);
        $cvs = $query->latest('updated_at')->paginate($perPage);

        return response()->json([
            'success' => true,
            'data' => $cvs,
        ]);
    }

    /**
     * Get current user's CVs.
     */
    public function myCvs()
    {
        $cvs = UserCv::with(['workExperiences', 'educationEntries', 'certifications', 'languages'])
            ->where('user_id', Auth::id())
            ->latest()
            ->get();

        return response()->json([
            'success' => true,
            'data' => $cvs,
        ]);
    }

    /**
     * Store a newly created CV.
     */
    public function store(StoreCvRequest $request)
    {
        try {
            $data = $request->validated();
            $data['user_id'] = Auth::id();

            Log::info('FreeCvController - Store CV - Validated Data', [
                'has_skills' => isset($data['skills']),
                'skills' => $data['skills'] ?? 'not set',
                'skills_type' => isset($data['skills']) ? gettype($data['skills']) : 'N/A',
                'skills_count' => isset($data['skills']) ? count($data['skills']) : 0,
                'all_keys' => array_keys($data),
            ]);

            $user = Auth::user();

            // If no full_name provided, use user's name
            if (empty($data['full_name'])) {
                $data['full_name'] = $user->name;
            }

            // If no email provided, use user's email
            if (empty($data['email'])) {
                $data['email'] = $user->email;
            }

            // If is_primary is true, unset other primary CVs
            if ($data['is_primary'] ?? false) {
                UserCv::where('user_id', Auth::id())->update(['is_primary' => false]);
            }

            // Extract relationship data
            $workExperiences = $data['work_experience'] ?? [];
            $education = $data['education'] ?? [];
            $certifications = $data['certifications'] ?? [];
            $languages = $data['languages'] ?? [];

            // Remove relationship data from main data array
            unset($data['work_experience'], $data['education'], $data['certifications'], $data['languages']);

            Log::info('FreeCvController - Data being passed to UserCv::create', [
                'has_skills' => isset($data['skills']),
                'skills' => $data['skills'] ?? 'not set',
                'skills_count' => isset($data['skills']) ? count($data['skills']) : 0,
                'all_keys' => array_keys($data),
            ]);

            $cv = UserCv::create($data);
            
            // Refresh to ensure we have the slug generated by boot method
            $cv->refresh();
            
            // Log for debugging
            Log::info('CV Created', [
                'id' => $cv->id,
                'slug' => $cv->slug,
                'title' => $cv->title,
                'full_name' => $cv->full_name,
            ]);

            // Create work experiences
            if (!empty($workExperiences)) {
                foreach ($workExperiences as $index => $experience) {
                    $cv->workExperiences()->create(array_merge($experience, ['order' => $index]));
                }
            }

            // Create education entries
            if (!empty($education)) {
                foreach ($education as $index => $edu) {
                    $cv->educationEntries()->create(array_merge($edu, ['order' => $index]));
                }
            }

            // Create certifications
            if (!empty($certifications)) {
                foreach ($certifications as $index => $cert) {
                    $cv->certifications()->create(array_merge($cert, ['order' => $index]));
                }
            }

            // Create languages
            if (!empty($languages)) {
                foreach ($languages as $index => $lang) {
                    $cv->languages()->create(array_merge($lang, ['order' => $index]));
                }
            }

            // Handle profile image upload
            if ($request->hasFile('profile_image')) {
                Log::info('Profile image detected', [
                    'has_file' => true,
                    'is_valid' => $request->file('profile_image')->isValid(),
                    'original_name' => $request->file('profile_image')->getClientOriginalName(),
                    'size' => $request->file('profile_image')->getSize(),
                ]);
                
                $path = $request->file('profile_image')->store('cvs/profiles', 'public');
                
                Log::info('Profile image stored', [
                    'path' => $path,
                ]);
                
                // Save the image path directly to the CV record
                $cv->update(['profile_image_path' => $path]);
                
                Log::info('Profile image path saved to CV', [
                    'cv_id' => $cv->id,
                    'path' => $path,
                ]);
            } else {
                Log::info('No profile image in request', [
                    'has_file' => $request->hasFile('profile_image'),
                    'all_files' => $request->allFiles(),
                ]);
            }

            return response()->json([
                'success' => true,
                'data' => $cv->load(['workExperiences', 'educationEntries', 'certifications', 'languages']),
                'message' => 'CV created successfully',
            ], 201);
        } catch (\Exception $e) {
            Log::error('CV Creation Failed', [
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString(),
                'request_data' => $request->except(['profile_image']),
            ]);
            
            return response()->json([
                'success' => false,
                'message' => 'Failed to create CV: ' . $e->getMessage(),
            ], 500);
        }
    }

    /**
     * Display the specified CV.
     * Accepts either a slug (string) or ID (numeric).
     */
    public function show($identifier)
    {
        $query = UserCv::with(['user', 'workExperiences', 'educationEntries', 'certifications', 'languages']);
        
        // Check if identifier is numeric (ID) or string (slug)
        if (is_numeric($identifier)) {
            $cv = $query->where('id', $identifier)->first();
        } else {
            $cv = $query->where('slug', $identifier)->first();
        }

        if (!$cv) {
            return response()->json([
                'success' => false,
                'message' => 'CV not found.'
            ], 404);
        }

        // Allow owner to view their own CV, or require CV to be public
        $isOwner = Auth::check() && $cv->belongsToUser(Auth::user());
        
        if (!$cv->is_public && !$isOwner) {
            return response()->json([
                'success' => false,
                'message' => 'This CV is private.'
            ], 403);
        }

        return response()->json([
            'success' => true,
            'data' => $cv,
        ]);
    }

    /**
     * Update the specified CV.
     */
    public function update(UpdateCvRequest $request, UserCv $cv)
    {
        // Check authorization
        if (!$cv->belongsToUser(Auth::user())) {
            return response()->json([
                'success' => false,
                'message' => 'Unauthorized'
            ], 403);
        }

        $data = $request->validated();
        
        // If is_primary is true, unset other primary CVs
        if (($data['is_primary'] ?? false) && !$cv->is_primary) {
            UserCv::where('user_id', Auth::id())
                ->where('id', '!=', $cv->id)
                ->update(['is_primary' => false]);
        }

        // Extract relationship data
        $workExperiences = $data['work_experience'] ?? null;
        $education = $data['education'] ?? null;
        $certifications = $data['certifications'] ?? null;
        $languages = $data['languages'] ?? null;

        // Remove relationship data from main data array
        unset($data['work_experience'], $data['education'], $data['certifications'], $data['languages']);
        
        $cv->update($data);

        // Update work experiences
        if ($workExperiences !== null) {
            $cv->workExperiences()->delete();
            foreach ($workExperiences as $index => $experience) {
                $cv->workExperiences()->create(array_merge($experience, ['order' => $index]));
            }
        }

        // Update education entries
        if ($education !== null) {
            $cv->educationEntries()->delete();
            foreach ($education as $index => $edu) {
                $cv->educationEntries()->create(array_merge($edu, ['order' => $index]));
            }
        }

        // Update certifications
        if ($certifications !== null) {
            $cv->certifications()->delete();
            foreach ($certifications as $index => $cert) {
                $cv->certifications()->create(array_merge($cert, ['order' => $index]));
            }
        }

        // Update languages
        if ($languages !== null) {
            $cv->languages()->delete();
            foreach ($languages as $index => $lang) {
                $cv->languages()->create(array_merge($lang, ['order' => $index]));
            }
        }

        // Handle profile image upload
        if ($request->hasFile('profile_image')) {
            // Delete old profile image if exists
            if ($cv->profile_image_path) {
                Storage::disk('public')->delete($cv->profile_image_path);
            }

            $path = $request->file('profile_image')->store('cvs/profiles', 'public');
            
            // Save the image path directly to the CV record
            $cv->update(['profile_image_path' => $path]);
        }

        return response()->json([
            'success' => true,
            'data' => $cv->fresh(['workExperiences', 'educationEntries', 'certifications', 'languages']),
            'message' => 'CV updated successfully',
        ]);
    }

    /**
     * Remove the specified CV.
     */
    public function destroy(UserCv $cv)
    {
        // Check authorization
        if (!$cv->belongsToUser(Auth::user())) {
            return response()->json([
                'success' => false,
                'message' => 'Unauthorized'
            ], 403);
        }

        // Delete all images
        foreach ($cv->images as $image) {
            Storage::disk('public')->delete($image->path);
        }

        $cv->delete();

        return response()->json([
            'success' => true,
            'message' => 'CV deleted successfully'
        ]);
    }



    /**
     * Set CV as primary.
     */
    public function setPrimary(UserCv $cv)
    {
        // Check authorization
        if (!$cv->belongsToUser(Auth::user())) {
            return response()->json([
                'message' => 'Unauthorized'
            ], 403);
        }

        $cv->update(['is_primary' => true]);

        return response()->json([
            'message' => 'CV set as primary successfully',
            'cv' => $cv,
        ]);
    }
}
