// Mocks generated by Mockito 5.4.4 from annotations
// in jobsiq_mobile/test/presentation/bloc/cvs_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:jobsiq_mobile/data/datasources/cv_remote_data_source.dart'
    as _i3;
import 'package:jobsiq_mobile/data/models/cv_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCvModel_0 extends _i1.SmartFake implements _i2.CvModel {
  _FakeCvModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CvRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCvRemoteDataSource extends _i1.Mock
    implements _i3.CvRemoteDataSource {
  MockCvRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.CvModel>> getMyCvs() => (super.noSuchMethod(
        Invocation.method(
          #getMyCvs,
          [],
        ),
        returnValue: _i4.Future<List<_i2.CvModel>>.value(<_i2.CvModel>[]),
      ) as _i4.Future<List<_i2.CvModel>>);

  @override
  _i4.Future<_i2.CvModel> getCvById(int? cvId) => (super.noSuchMethod(
        Invocation.method(
          #getCvById,
          [cvId],
        ),
        returnValue: _i4.Future<_i2.CvModel>.value(_FakeCvModel_0(
          this,
          Invocation.method(
            #getCvById,
            [cvId],
          ),
        )),
      ) as _i4.Future<_i2.CvModel>);

  @override
  _i4.Future<_i2.CvModel> createCv(Map<String, dynamic>? cvData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCv,
          [cvData],
        ),
        returnValue: _i4.Future<_i2.CvModel>.value(_FakeCvModel_0(
          this,
          Invocation.method(
            #createCv,
            [cvData],
          ),
        )),
      ) as _i4.Future<_i2.CvModel>);

  @override
  _i4.Future<_i2.CvModel> updateCv(
    int? cvId,
    Map<String, dynamic>? cvData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCv,
          [
            cvId,
            cvData,
          ],
        ),
        returnValue: _i4.Future<_i2.CvModel>.value(_FakeCvModel_0(
          this,
          Invocation.method(
            #updateCv,
            [
              cvId,
              cvData,
            ],
          ),
        )),
      ) as _i4.Future<_i2.CvModel>);

  @override
  _i4.Future<void> deleteCv(int? cvId) => (super.noSuchMethod(
        Invocation.method(
          #deleteCv,
          [cvId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setPrimaryCv(int? cvId) => (super.noSuchMethod(
        Invocation.method(
          #setPrimaryCv,
          [cvId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
