// Mocks generated by Mockito 5.4.4 from annotations
// in jobsiq_mobile/test/presentation/bloc/jobs_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:jobsiq_mobile/core/error/failures.dart' as _i6;
import 'package:jobsiq_mobile/data/datasources/job_application_remote_data_source.dart'
    as _i11;
import 'package:jobsiq_mobile/data/datasources/saved_job_remote_data_source.dart'
    as _i9;
import 'package:jobsiq_mobile/data/models/job_model.dart' as _i10;
import 'package:jobsiq_mobile/domain/entities/job_entity.dart' as _i8;
import 'package:jobsiq_mobile/domain/repositories/job_repository.dart' as _i2;
import 'package:jobsiq_mobile/domain/usecases/jobs/get_featured_jobs_usecase.dart'
    as _i7;
import 'package:jobsiq_mobile/domain/usecases/jobs/get_jobs_usecase.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeJobRepository_0 extends _i1.SmartFake implements _i2.JobRepository {
  _FakeJobRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetJobsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetJobsUseCase extends _i1.Mock implements _i4.GetJobsUseCase {
  MockGetJobsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.JobRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeJobRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.JobRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i2.JobsResult>> call(
          _i4.GetJobsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i2.JobsResult>>.value(
            _FakeEither_1<_i6.Failure, _i2.JobsResult>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i2.JobsResult>>);
}

/// A class which mocks [GetFeaturedJobsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFeaturedJobsUseCase extends _i1.Mock
    implements _i7.GetFeaturedJobsUseCase {
  MockGetFeaturedJobsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.JobRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeJobRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.JobRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i8.JobEntity>>> call(
          _i7.GetFeaturedJobsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i8.JobEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i8.JobEntity>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i8.JobEntity>>>);
}

/// A class which mocks [SavedJobRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSavedJobRemoteDataSource extends _i1.Mock
    implements _i9.SavedJobRemoteDataSource {
  MockSavedJobRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i10.JobModel>> getSavedJobs() => (super.noSuchMethod(
        Invocation.method(
          #getSavedJobs,
          [],
        ),
        returnValue: _i5.Future<List<_i10.JobModel>>.value(<_i10.JobModel>[]),
      ) as _i5.Future<List<_i10.JobModel>>);

  @override
  _i5.Future<bool> toggleSaveJob(int? jobId) => (super.noSuchMethod(
        Invocation.method(
          #toggleSaveJob,
          [jobId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> checkIfJobSaved(int? jobId) => (super.noSuchMethod(
        Invocation.method(
          #checkIfJobSaved,
          [jobId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [JobApplicationRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockJobApplicationRemoteDataSource extends _i1.Mock
    implements _i11.JobApplicationRemoteDataSource {
  MockJobApplicationRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> applyForJob(
    String? jobSlug,
    int? cvId,
    String? coverLetter,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #applyForJob,
          [
            jobSlug,
            cvId,
            coverLetter,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> checkIfApplied(String? jobSlug) => (super.noSuchMethod(
        Invocation.method(
          #checkIfApplied,
          [jobSlug],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<Map<String, dynamic>> getMyApplications({
    String? status,
    String? search,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyApplications,
          [],
          {
            #status: status,
            #search: search,
          },
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);
}

/// A class which mocks [JobRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockJobRepository extends _i1.Mock implements _i2.JobRepository {
  MockJobRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i2.JobsResult>> getJobs({
    int? page = 1,
    int? perPage = 15,
    String? search,
    String? location,
    List<String>? employmentTypes,
    List<String>? experienceLevels,
    bool? isRemote,
    String? category,
    double? salaryMin,
    String? company,
    String? sort,
    int? seed,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getJobs,
          [],
          {
            #page: page,
            #perPage: perPage,
            #search: search,
            #location: location,
            #employmentTypes: employmentTypes,
            #experienceLevels: experienceLevels,
            #isRemote: isRemote,
            #category: category,
            #salaryMin: salaryMin,
            #company: company,
            #sort: sort,
            #seed: seed,
          },
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i2.JobsResult>>.value(
            _FakeEither_1<_i6.Failure, _i2.JobsResult>(
          this,
          Invocation.method(
            #getJobs,
            [],
            {
              #page: page,
              #perPage: perPage,
              #search: search,
              #location: location,
              #employmentTypes: employmentTypes,
              #experienceLevels: experienceLevels,
              #isRemote: isRemote,
              #category: category,
              #salaryMin: salaryMin,
              #company: company,
              #sort: sort,
              #seed: seed,
            },
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i2.JobsResult>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i8.JobEntity>>> getFeaturedJobs(
          {int? limit = 6}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFeaturedJobs,
          [],
          {#limit: limit},
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i8.JobEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i8.JobEntity>>(
          this,
          Invocation.method(
            #getFeaturedJobs,
            [],
            {#limit: limit},
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i8.JobEntity>>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i8.JobEntity>> getJobBySlug(
          String? slug) =>
      (super.noSuchMethod(
        Invocation.method(
          #getJobBySlug,
          [slug],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i8.JobEntity>>.value(
            _FakeEither_1<_i6.Failure, _i8.JobEntity>(
          this,
          Invocation.method(
            #getJobBySlug,
            [slug],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i8.JobEntity>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i8.JobEntity>>> getMyJobs() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyJobs,
          [],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i8.JobEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i8.JobEntity>>(
          this,
          Invocation.method(
            #getMyJobs,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i8.JobEntity>>>);
}
