// Mocks generated by Mockito 5.4.4 from annotations
// in jobsiq_mobile/test/presentation/bloc/saved_jobs_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:jobsiq_mobile/data/datasources/saved_job_remote_data_source.dart'
    as _i2;
import 'package:jobsiq_mobile/data/models/job_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SavedJobRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSavedJobRemoteDataSource extends _i1.Mock
    implements _i2.SavedJobRemoteDataSource {
  MockSavedJobRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.JobModel>> getSavedJobs() => (super.noSuchMethod(
        Invocation.method(
          #getSavedJobs,
          [],
        ),
        returnValue: _i3.Future<List<_i4.JobModel>>.value(<_i4.JobModel>[]),
      ) as _i3.Future<List<_i4.JobModel>>);

  @override
  _i3.Future<bool> toggleSaveJob(int? jobId) => (super.noSuchMethod(
        Invocation.method(
          #toggleSaveJob,
          [jobId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> checkIfJobSaved(int? jobId) => (super.noSuchMethod(
        Invocation.method(
          #checkIfJobSaved,
          [jobId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
