export const companyCategories = [
  "Information Technology (IT)",
  "Software Development",
  "Education & Training",
  "Healthcare & Medical",
  "Finance & Banking",
  "Insurance & Investment",
  "Construction & Engineering",
  "Architecture & Design",
  "Oil & Gas / Energy",
  "Retail & E-Commerce",
  "Manufacturing & Production",
  "Transportation & Logistics",
  "Automotive Industry",
  "Government & Public Sector",
  "Telecommunications",
  "Hospitality & Tourism",
  "Media & Entertainment",
  "Agriculture & Food",
  "NGO & Non-Profit",
  "Legal & Consulting",
  "Real Estate",
  "Security & Defense",
  "Marketing & Advertising",
  "Environmental Services",
  "Human Resources & Recruitment",
  "Research & Development",
  "Technology Services",
  "Creative Arts & Design",
  "Import & Export",
  "Customer Support & Call Centers",
];
