export const countryCodesAndNames = {
  AF: { en: "Afghanistan", ar: "أفغانستان" },
  AL: { en: "Albania", ar: "ألبانيا" },
  DZ: { en: "Algeria", ar: "الجزائر" },
  AD: { en: "Andorra", ar: "أندورا" },
  AO: { en: "Angola", ar: "أنغولا" },
  AR: { en: "Argentina", ar: "الأرجنتين" },
  AM: { en: "Armenia", ar: "أرمينيا" },
  AU: { en: "Australia", ar: "أستراليا" },
  AT: { en: "Austria", ar: "النمسا" },
  AZ: { en: "Azerbaijan", ar: "أذربيجان" },
  BH: { en: "Bahrain", ar: "البحرين" },
  BD: { en: "Bangladesh", ar: "بنغلاديش" },
  BY: { en: "Belarus", ar: "بيلاروسيا" },
  BE: { en: "Belgium", ar: "بلجيكا" },
  BZ: { en: "Belize", ar: "بليز" },
  BJ: { en: "Benin", ar: "بنين" },
  BT: { en: "Bhutan", ar: "بوتان" },
  BO: { en: "Bolivia", ar: "بوليفيا" },
  BA: { en: "Bosnia and Herzegovina", ar: "البوسنة والهرسك" },
  BW: { en: "Botswana", ar: "بوتسوانا" },
  BR: { en: "Brazil", ar: "البرازيل" },
  BN: { en: "Brunei", ar: "بروناي" },
  BG: { en: "Bulgaria", ar: "بلغاريا" },
  BF: { en: "Burkina Faso", ar: "بوركينا فاسو" },
  BI: { en: "Burundi", ar: "بوروندي" },
  KH: { en: "Cambodia", ar: "كمبوديا" },
  CM: { en: "Cameroon", ar: "الكاميرون" },
  CA: { en: "Canada", ar: "كندا" },
  CV: { en: "Cabo Verde", ar: "الرأس الأخضر" },
  CF: { en: "Central African Republic", ar: "جمهورية أفريقيا الوسطى" },
  TD: { en: "Chad", ar: "تشاد" },
  CL: { en: "Chile", ar: "تشيلي" },
  CN: { en: "China", ar: "الصين" },
  CO: { en: "Colombia", ar: "كولومبيا" },
  KM: { en: "Comoros", ar: "جزر القمر" },
  CG: { en: "Congo", ar: "الكونغو" },
  CR: { en: "Costa Rica", ar: "كوستاريكا" },
  HR: { en: "Croatia", ar: "كرواتيا" },
  CU: { en: "Cuba", ar: "كوبا" },
  CY: { en: "Cyprus", ar: "قبرص" },
  CZ: { en: "Czech Republic", ar: "التشيك" },
  DK: { en: "Denmark", ar: "الدنمارك" },
  DJ: { en: "Djibouti", ar: "جيبوتي" },
  DM: { en: "Dominica", ar: "دومينيكا" },
  DO: { en: "Dominican Republic", ar: "جمهورية الدومينيكان" },
  EC: { en: "Ecuador", ar: "الإكوادور" },
  EG: { en: "Egypt", ar: "مصر" },
  SV: { en: "El Salvador", ar: "السلفادور" },
  GQ: { en: "Equatorial Guinea", ar: "غينيا الاستوائية" },
  ER: { en: "Eritrea", ar: "إريتريا" },
  EE: { en: "Estonia", ar: "إستونيا" },
  ET: { en: "Ethiopia", ar: "إثيوبيا" },
  FJ: { en: "Fiji", ar: "فيجي" },
  FI: { en: "Finland", ar: "فنلندا" },
  FR: { en: "France", ar: "فرنسا" },
  GA: { en: "Gabon", ar: "الغابون" },
  GM: { en: "Gambia", ar: "غامبيا" },
  GE: { en: "Georgia", ar: "جورجيا" },
  DE: { en: "Germany", ar: "ألمانيا" },
  GH: { en: "Ghana", ar: "غانا" },
  GR: { en: "Greece", ar: "اليونان" },
  GD: { en: "Grenada", ar: "غرينادا" },
  GT: { en: "Guatemala", ar: "غواتيمالا" },
  GN: { en: "Guinea", ar: "غينيا" },
  GW: { en: "Guinea-Bissau", ar: "غينيا بيساو" },
  GY: { en: "Guyana", ar: "غيانا" },
  HT: { en: "Haiti", ar: "هايتي" },
  HN: { en: "Honduras", ar: "هندوراس" },
  HU: { en: "Hungary", ar: "المجر" },
  IS: { en: "Iceland", ar: "آيسلندا" },
  IN: { en: "India", ar: "الهند" },
  ID: { en: "Indonesia", ar: "إندونيسيا" },
  IR: { en: "Iran", ar: "إيران" },
  IQ: { en: "Iraq", ar: "العراق" },
  IE: { en: "Ireland", ar: "أيرلندا" },
  IL: { en: "Israel", ar: "إسرائيل" },
  IT: { en: "Italy", ar: "إيطاليا" },
  CI: { en: "Ivory Coast", ar: "ساحل العاج" },
  JM: { en: "Jamaica", ar: "جامايكا" },
  JP: { en: "Japan", ar: "اليابان" },
  JO: { en: "Jordan", ar: "الأردن" },
  KZ: { en: "Kazakhstan", ar: "كازاخستان" },
  KE: { en: "Kenya", ar: "كينيا" },
  KI: { en: "Kiribati", ar: "كيريباتي" },
  KP: { en: "North Korea", ar: "كوريا الشمالية" },
  KR: { en: "South Korea", ar: "كوريا الجنوبية" },
  KW: { en: "Kuwait", ar: "الكويت" },
  KG: { en: "Kyrgyzstan", ar: "قيرغيزستان" },
  LA: { en: "Laos", ar: "لاوس" },
  LV: { en: "Latvia", ar: "لاتفيا" },
  LB: { en: "Lebanon", ar: "لبنان" },
  LS: { en: "Lesotho", ar: "ليسوتو" },
  LR: { en: "Liberia", ar: "ليبيريا" },
  LY: { en: "Libya", ar: "ليبيا" },
  LI: { en: "Liechtenstein", ar: "ليختنشتاين" },
  LT: { en: "Lithuania", ar: "ليتوانيا" },
  LU: { en: "Luxembourg", ar: "لوكسمبورغ" },
  MG: { en: "Madagascar", ar: "مدغشقر" },
  MW: { en: "Malawi", ar: "مالاوي" },
  MY: { en: "Malaysia", ar: "ماليزيا" },
  MV: { en: "Maldives", ar: "المالديف" },
  ML: { en: "Mali", ar: "مالي" },
  MT: { en: "Malta", ar: "مالطا" },
  MH: { en: "Marshall Islands", ar: "جزر مارشال" },
  MR: { en: "Mauritania", ar: "موريتانيا" },
  MU: { en: "Mauritius", ar: "موريشيوس" },
  MX: { en: "Mexico", ar: "المكسيك" },
  FM: { en: "Micronesia", ar: "ميكرونيزيا" },
  MD: { en: "Moldova", ar: "مولدوفا" },
  MC: { en: "Monaco", ar: "موناكو" },
  MN: { en: "Mongolia", ar: "منغوليا" },
  ME: { en: "Montenegro", ar: "الجبل الأسود" },
  MA: { en: "Morocco", ar: "المغرب" },
  MZ: { en: "Mozambique", ar: "موزمبيق" },
  MM: { en: "Myanmar", ar: "ميانمار" },
  NA: { en: "Namibia", ar: "ناميبيا" },
  NR: { en: "Nauru", ar: "ناورو" },
  NP: { en: "Nepal", ar: "نيبال" },
  NL: { en: "Netherlands", ar: "هولندا" },
  NZ: { en: "New Zealand", ar: "نيوزيلندا" },
  NI: { en: "Nicaragua", ar: "نيكاراغوا" },
  NE: { en: "Niger", ar: "النيجر" },
  NG: { en: "Nigeria", ar: "نيجيريا" },
  NO: { en: "Norway", ar: "النرويج" },
  OM: { en: "Oman", ar: "عمان" },
  PK: { en: "Pakistan", ar: "باكستان" },
  PW: { en: "Palau", ar: "بالاو" },
  PS: { en: "Palestine", ar: "فلسطين" },
  PA: { en: "Panama", ar: "بنما" },
  PG: { en: "Papua New Guinea", ar: "بابوا غينيا الجديدة" },
  PY: { en: "Paraguay", ar: "باراغواي" },
  PE: { en: "Peru", ar: "بيرو" },
  PH: { en: "Philippines", ar: "الفلبين" },
  PL: { en: "Poland", ar: "بولندا" },
  PT: { en: "Portugal", ar: "البرتغال" },
  QA: { en: "Qatar", ar: "قطر" },
  RO: { en: "Romania", ar: "رومانيا" },
  RU: { en: "Russia", ar: "روسيا" },
  RW: { en: "Rwanda", ar: "رواندا" },
  KN: { en: "Saint Kitts and Nevis", ar: "سانت كيتس ونيفيس" },
  LC: { en: "Saint Lucia", ar: "سانت لوسيا" },
  VC: { en: "Saint Vincent and the Grenadines", ar: "سانت فنسنت والغرينادين" },
  WS: { en: "Samoa", ar: "ساموا" },
  SM: { en: "San Marino", ar: "سان مارينو" },
  ST: { en: "Sao Tome and Principe", ar: "ساو تومي وبرينسيبي" },
  SA: { en: "Saudi Arabia", ar: "المملكة العربية السعودية" },
  SN: { en: "Senegal", ar: "السنغال" },
  RS: { en: "Serbia", ar: "صربيا" },
  SC: { en: "Seychelles", ar: "سيشل" },
  SL: { en: "Sierra Leone", ar: "سيراليون" },
  SG: { en: "Singapore", ar: "سنغافورة" },
  SK: { en: "Slovakia", ar: "سلوفاكيا" },
  SI: { en: "Slovenia", ar: "سلوفينيا" },
  SB: { en: "Solomon Islands", ar: "جزر سليمان" },
  SO: { en: "Somalia", ar: "الصومال" },
  ZA: { en: "South Africa", ar: "جنوب أفريقيا" },
  SS: { en: "South Sudan", ar: "جنوب السودان" },
  ES: { en: "Spain", ar: "إسبانيا" },
  LK: { en: "Sri Lanka", ar: "سريلانكا" },
  SD: { en: "Sudan", ar: "السودان" },
  SR: { en: "Suriname", ar: "سورينام" },
  SZ: { en: "Eswatini", ar: "إسواتيني" },
  SE: { en: "Sweden", ar: "السويد" },
  CH: { en: "Switzerland", ar: "سويسرا" },
  SY: { en: "Syria", ar: "سوريا" },
  TW: { en: "Taiwan", ar: "تايوان" },
  TJ: { en: "Tajikistan", ar: "طاجيكستان" },
  TZ: { en: "Tanzania", ar: "تنزانيا" },
  TH: { en: "Thailand", ar: "تايلاند" },
  TL: { en: "East Timor", ar: "تيمور الشرقية" },
  TG: { en: "Togo", ar: "توغو" },
  TO: { en: "Tonga", ar: "تونغا" },
  TT: { en: "Trinidad and Tobago", ar: "ترينيداد وتوباغو" },
  TN: { en: "Tunisia", ar: "تونس" },
  TR: { en: "Turkey", ar: "تركيا" },
  TM: { en: "Turkmenistan", ar: "تركمانستان" },
  TV: { en: "Tuvalu", ar: "توفالو" },
  UG: { en: "Uganda", ar: "أوغندا" },
  UA: { en: "Ukraine", ar: "أوكرانيا" },
  AE: { en: "United Arab Emirates", ar: "الإمارات العربية المتحدة" },
  GB: { en: "United Kingdom", ar: "المملكة المتحدة" },
  US: { en: "United States", ar: "الولايات المتحدة" },
  UY: { en: "Uruguay", ar: "أوروغواي" },
  UZ: { en: "Uzbekistan", ar: "أوزبكستان" },
  VU: { en: "Vanuatu", ar: "فانواتو" },
  VA: { en: "Vatican City", ar: "الفاتيكان" },
  VE: { en: "Venezuela", ar: "فنزويلا" },
  VN: { en: "Vietnam", ar: "فيتنام" },
  YE: { en: "Yemen", ar: "اليمن" },
  ZM: { en: "Zambia", ar: "زامبيا" },
  ZW: { en: "Zimbabwe", ar: "زيمبابوي" },
}

// Helper function to get country names by locale
export const getCountries = (locale: 'en' | 'ar' = 'en'): string[] => {
  return Object.values(countryCodesAndNames).map((country) => country[locale])
}

// Legacy export for backward compatibility
export const countries = Object.values(countryCodesAndNames).map((country) => country.en)
